name: misspell fixer
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Whitelist some directories and files
      run: |
        echo "\
        ^./.github/workflows
        ^./.mailmap
        ^./docs/2/configuration/_disabled.md:9:existant
        ^./docs/2/modules/alltime.md:11:ALLTIME
        ^./docs/2/modules/alltime.md:27:ALLTIME
        ^./docs/2/modules/alltime.md:2:alltime
        ^./docs/2/modules/alltime.md:7:alltime
        ^./docs/2/modules/index.md:20:alltime
        ^./docs/3/change-log.md:19:customising
        ^./docs/3/change-log.md:359:customising
        ^./docs/3/change-log.md:363:customising
        ^./docs/3/modules/alltime.md:16:alltime
        ^./docs/3/modules/alltime.md:25:ALLTIME
        ^./docs/3/modules/alltime.md:2:alltime
        ^./docs/3/modules/alltime.md:5:alltime
        ^./docs/3/modules/alltime.md:9:ALLTIME
        ^./docs/3/modules/index.md:18:ALLTIME
        ^./docs/3/modules/index.md:18:alltime
        ^./docs/4/breaking-changes.md:13:existant\
        " > ${{ runner.workspace }}/inspircd-docs/.misspell-fixer.ignore
    - uses: sobolevn/misspell-fixer-action@master
      with:
        options: '-rvnfuRVD .'
    - uses: peter-evans/create-pull-request@v2.4.4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
#        author: 'InspIRCd Robot <noreply@inspircd.org>'
#        commiter: 'InspIRCd Robot <noreply@inspircd.org>'
#        commit-message: 'Fixes by misspell-fixer'
#        title: 'Typos fix by misspell-fixer'
#        reviewers: 'genius3000'
